### PR TITLE
Adding stylelint #105

### PR DESCRIPTION
**Pull request by Melodycel**

### CODE REVIEW

**Comment by astanik** [comment]
The code coverage can be ignored, because the LeoModal component will be removed in the future.

**Comment by PiaSophieBe** [comment]
I would like to do the review.

**Review by PiaSophieBe — COMMENTED** [review]
These errors occurred during execution: 

Bildschirmfoto 2024-07-07 um 17 36 17


Why are these properties ignored? - "user-select", "appearance", "border-radius", "box-sizing", "transition", "box-shadow", "flex-flow", "flex-grow", "flex-wrap", "align-items", "flex-direction"

**Comment by Melodycel** [comment]
These errors don't occur when I run it. Do you have the right version? Because in the stylelintrc.json is the rule no-empty-source set null. So the no-empty-source errors should not occur.

The stylelint rule property-no-vendor-prefix used to cause errors with the non-standard vendor-prefixes. Thats why I ignored these properties for non-standard vendor-prefixes. But it seems like it is not used anymore because without this customizations it still shows no errors. So the lines from 7 to 10 in the stylelintrc.json can be removed.

**Comment by astanik** [comment]
@PiaSophieBe Please use the review functionality of GitHub...

grafik

**Review by PiaSophieBe — APPROVED** [review]
Great work, everything is looking good!

**Pull request merged**
