### PR TITLE
Feature/add home navigation

### PR DESCRIPTION
**Pull request by s0571584**
merged remsfal main into my branch and commited changes

### CODE REVIEW

**Comment by astanik** [comment]
@s0571584 Please finish your good first issue. The deadline was already on Monday!

**Comment by s0571584** [comment]
When I pull requested last week every test was green, so I thought I was done. I can't recreate the errors locally to fix them, I am trying to fix the errors I see here on GitHub. 😅But I will do it!🫡🫡

**Comment by astanik** [comment]
@s0571584 You are almost there. All that's missing is a test to achieve code coverage https://sonarcloud.io/summary/new_code?id=remsfal_remsfal-frontend&pullRequest=271

Here you can find a good example on how to klick the button https://github.com/remsfal/remsfal-frontend/blob/f11cf47e5e3193e54e8535448e559e24a284ddf7/test/layout/AppTopbar.spec.ts#L43

**Review by astanik — APPROVED** [review]
Good job!

**Pull request merged**
